// Builds dist/ from the DTCG source in src/.
// Style Dictionary parses, resolves references and applies transforms; this file
// assembles the outputs so mode files can become media queries and context selectors.
import { mkdirSync, readFileSync, readdirSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import StyleDictionary from 'style-dictionary';

const root = dirname(fileURLToPath(import.meta.url));
const src = join(root, 'src');
const dist = join(root, 'dist');
const PREFIX = 'ds';

// Figma path segments keep their spelling in source ("Font-Weight.Semi Bold");
// CSS names are lowercased with spaces as hyphens: --ds-font-weight-semi-bold.
export const cssName = (path) =>
  [PREFIX, ...path].map((seg) => String(seg).toLowerCase().replace(/\s+/g, '-')).join('-');

const figma = (token) => token.$extensions?.['com.figma'] ?? {};
const refPath = (value) => {
  const m = typeof value === 'string' && value.match(/^\{([^}]+)\}$/);
  return m ? m[1].split('.') : null;
};

StyleDictionary.registerTransform({
  name: 'ds/name',
  type: 'name',
  transform: (token) => cssName(token.path).slice(PREFIX.length + 1),
});

// Figma aliases can carry an opacity (percent). Resolved outputs get rgba();
// CSS keeps the reference through color-mix() in the format below.
StyleDictionary.registerTransform({
  name: 'ds/alias-opacity',
  type: 'value',
  transitive: true,
  filter: (token) => figma(token).aliasOpacity !== undefined,
  transform: (token) => {
    const hex = String(token.$value).replace('#', '');
    const [r, g, b] = [0, 2, 4].map((i) => parseInt(hex.slice(i, i + 2), 16));
    return `rgba(${r}, ${g}, ${b}, ${figma(token).aliasOpacity / 100})`;
  },
});

// Font families get the metric-adjusted fallback face from @jpm1475/ds-fonts when it
// declares one: "THICCCBOI", sans-serif -> "THICCCBOI", "THICCCBOI Fallback", system-ui, sans-serif.
const fontsCss = readFileSync(join(root, '..', 'fonts', 'fonts.css'), 'utf8');
const fallbackFaces = new Set(
  [...fontsCss.matchAll(/font-family:\s*"([^"]+) Fallback"/g)].map((m) => m[1]),
);

StyleDictionary.registerTransform({
  name: 'ds/font-stack',
  type: 'value',
  filter: (token) => token.$type === 'fontFamily' && !refPath(token.original.$value),
  transform: (token) => {
    const [first, ...rest] = String(token.$value)
      .split(',')
      .map((s) => s.trim());
    const family = first.replace(/^"|"$/g, '');
    if (!fallbackFaces.has(family)) return token.$value;
    return [
      first,
      `"${family} Fallback"`,
      'system-ui',
      ...rest.filter((f) => f !== 'system-ui'),
    ].join(', ');
  },
});

const modeFiles = (dir) =>
  readdirSync(join(src, dir))
    .filter((f) => f.endsWith('.json'))
    .map((f) => f.replace(/\.json$/, ''));

const breakpoints = JSON.parse(readFileSync(join(root, 'breakpoints.json'), 'utf8'));
const typeModes = modeFiles('typography-semantics').sort((a, b) => breakpoints[a] - breakpoints[b]);
const iconModes = modeFiles('icon-context');
const ICON_DEFAULT = 'primary';

for (const mode of typeModes) {
  if (breakpoints[mode] === undefined)
    throw new Error(`breakpoints.json has no width for mode "${mode}"`);
}
if (!iconModes.includes(ICON_DEFAULT))
  throw new Error(`icon-context needs a "${ICON_DEFAULT}" mode file`);

const SHARED = ['primitives/*.json', 'typography-primitives/*.json', 'semantics/*.json'];

async function tokensFor({ typeMode, iconMode }) {
  const sd = new StyleDictionary({
    source: [
      ...SHARED,
      `typography-semantics/${typeMode}.json`,
      `icon-context/${iconMode}.json`,
    ].map((g) => join(src, g)),
    platforms: { ds: { transforms: ['ds/name', 'ds/font-stack', 'ds/alias-opacity'] } },
    log: { verbosity: 'silent', warnings: 'error' },
  });
  return sd.getPlatformTokens('ds');
}

// The CSS value: a var() of the referenced token, or the raw value for primitives.
function cssValue(token) {
  const ref = refPath(token.original.$value);
  if (!ref) return String(token.$value);
  const v = `var(--${cssName(ref)})`;
  const opacity = figma(token).aliasOpacity;
  return opacity === undefined ? v : `color-mix(in srgb, ${v} ${opacity}%, transparent)`;
}

const decl = (t, indent) => `${indent}--${cssName(t.path)}: ${cssValue(t)};`;
const byCollection = (all, name) => all.filter((t) => figma(t).collection === name);
const COLLECTION_ORDER = [
  'primitives',
  'typography-primitives',
  'semantics',
  'typography-semantics',
  'icon-context',
];

const base = await tokensFor({ typeMode: typeModes[0], iconMode: ICON_DEFAULT });
const all = base.allTokens;

// --- tokens.css ---------------------------------------------------------------
const css = ['/* Generated by @jpm1475/ds-tokens. Do not edit. */', ':root {'];
for (const col of COLLECTION_ORDER) {
  css.push(`  /* ${col} */`, ...byCollection(all, col).map((t) => decl(t, '  ')));
}
css.push('}');

const baseType = new Map(
  byCollection(all, 'typography-semantics').map((t) => [t.name, cssValue(t)]),
);
const typeByMode = { [typeModes[0]]: base };
for (const mode of typeModes.slice(1)) {
  const d = await tokensFor({ typeMode: mode, iconMode: ICON_DEFAULT });
  typeByMode[mode] = d;
  const changed = byCollection(d.allTokens, 'typography-semantics').filter(
    (t) => baseType.get(t.name) !== cssValue(t),
  );
  if (changed.length === 0) continue;
  css.push(
    '',
    `/* typography-semantics: ${mode} */`,
    `@media (min-width: ${breakpoints[mode]}px) {`,
    '  :root {',
  );
  css.push(...changed.map((t) => decl(t, '    ')), '  }', '}');
}

const iconByMode = { [ICON_DEFAULT]: base };
for (const mode of iconModes.filter((m) => m !== ICON_DEFAULT)) {
  const d = await tokensFor({ typeMode: typeModes[0], iconMode: mode });
  iconByMode[mode] = d;
  css.push(
    '',
    `[data-icon-context="${mode}"] {`,
    ...byCollection(d.allTokens, 'icon-context').map((t) => decl(t, '  ')),
    '}',
  );
}

// --- JSON and JS --------------------------------------------------------------
const nested = (tokens) => {
  const out = {};
  for (const t of tokens) {
    let node = out;
    t.path.slice(0, -1).forEach((seg) => (node = node[seg] ??= {}));
    node[t.path.at(-1)] = t.$value;
  }
  return out;
};

const tokensJson = nested(all);
const typography = Object.fromEntries(
  typeModes.map((m) => [
    m,
    nested(byCollection(typeByMode[m].allTokens, 'typography-semantics')).type ?? {},
  ]),
);
const iconContexts = Object.fromEntries(
  iconModes.map((m) => [
    m,
    nested(byCollection(iconByMode[m].allTokens, 'icon-context')).icon ?? {},
  ]),
);
const tierMap = Object.fromEntries(
  COLLECTION_ORDER.flatMap((col) =>
    byCollection(all, col).map((t) => [`--${cssName(t.path)}`, col]),
  ),
);

const toType = (v, indent = '') => {
  if (v === null || typeof v !== 'object') return JSON.stringify(v);
  const inner = `${indent}  `;
  const lines = Object.entries(v).map(
    ([k, val]) => `${inner}readonly ${JSON.stringify(k)}: ${toType(val, inner)};`,
  );
  return `{\n${lines.join('\n')}\n${indent}}`;
};

const exportsMap = { tokens: tokensJson, breakpoints, typography, iconContexts, tierMap };
const js = Object.entries(exportsMap).map(
  ([k, v]) => `export const ${k} = ${JSON.stringify(v, null, 2)};`,
);
const dts = Object.entries(exportsMap).map(([k, v]) => `export declare const ${k}: ${toType(v)};`);

mkdirSync(dist, { recursive: true });
const header = '// Generated by @jpm1475/ds-tokens. Do not edit.\n';
writeFileSync(join(dist, 'tokens.css'), css.join('\n') + '\n');
writeFileSync(join(dist, 'tokens.json'), JSON.stringify(tokensJson, null, 2) + '\n');
writeFileSync(join(dist, 'tier-map.json'), JSON.stringify(tierMap, null, 2) + '\n');
writeFileSync(join(dist, 'index.js'), header + js.join('\n\n') + '\n');
writeFileSync(join(dist, 'index.d.ts'), header + dts.join('\n\n') + '\n');

console.log(
  `tokens: ${all.length} base tokens, ${Object.keys(tierMap).length} CSS variables, modes ${typeModes.join('/')}`,
);
